# Configuración básica de Serenity
# Driver por defecto
webdriver.driver=chrome
# Directorio donde se generan los reportes
serenity.outputDirectory=target/site/serenity
# Timeout por defecto
webdriver.timeouts.implicitlywait=5000
# Base urls (usar en tareas si se requiere)
selenium.base.url=https://selenium.dev
reqres.base.url=https://reqres.in