webdriver.driver=chrome
serenity.outputDirectory=target/site/serenity
serenity.parallel=false
webdriver.timeouts.implicitlywait=5000
selenium.base.url=https://selenium.dev
reqres.base.url=https://reqres.in